ИУ5-23М Добровольский Андрей

Вариант 4

**Номер задачи №1 - 4.** (Для набора данных проведите кодирование одного (произвольного) категориального признака с использованием метода "label encoding".)

**Номер задачи №2 - 24.** (Для набора данных для одного (произвольного) числового признака проведите обнаружение и удаление выбросов на основе 5% и 95% квантилей.)

Задача 4

In [3]:
!pip install pandas scikit-learn

Collecting pandas
  Using cached pandas-3.0.2-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting scikit-learn
  Using cached scikit_learn-1.8.0-cp314-cp314-win_amd64.whl.metadata (11 kB)
Collecting numpy>=2.3.3 (from pandas)
  Using cached numpy-2.4.4-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Using cached tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting scipy>=1.10.0 (from scikit-learn)
  Using cached scipy-1.17.1-cp314-cp314-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: six>=1.5 in .\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.2-cp314-cp314-win_amd64.whl (9.9 MB)
Using cached scikit_learn-1.8.0-cp314-cp314-win_amd64.whl (8.1 MB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Using cached numpy-2.4.4-cp314-cp314-win_amd64.whl (12.4 MB)
Using cached scipy-1.17.1-cp314-cp314-win_amd64.whl (37.3 MB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Using cached tzdata-2026.2-py2.py3-none-any.whl (349 kB)
Installing collected packages: tzdata, threadpoolctl, numpy, joblib, scipy, pandas, scikit-learn

   ---------------------------------------- 0/7 [tzdata]
   ---------------------------------------- 0/7 [tzdata]
   ---------------------------------------- 0/7 [tzdata]
   ---------------------------------------- 0/7 [tzdata]
   ---------------------------------------- 0/7 [tzdata]
   ---------------------------------------- 0/7 [tzdata]
   ---------------------------------------- 0/7 [tzdata]
   ----- ---------------------------------- 1/7 [threadpoolctl]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------------- ---------------------- 3/7 [joblib]
   ----------------- ---------------------- 3/7 [joblib]
   ----------------- ---------------------- 3/7 [joblib]
   ----------------- ---------------------- 3/7 [joblib]
   ----------------- ---------------------- 3/7 [joblib]
   ----------------- ---------------------- 3/7 [joblib]
   ----------------- ---------------------- 3/7 [joblib]
   ----------------- ---------------------- 3/7 [joblib]
   ----------------- ---------------------- 3/7 [joblib]
   ----------------- ---------------------- 3/7 [joblib]
   ----------------- ---------------------- 3/7 [joblib]
   ----------------- ---------------------- 3/7 [joblib]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]

In [4]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [5]:
df=pd.read_csv('data.csv')
df.head()

         Date   Open   High    Low  Close   Adj Close  Volume
0  2012-01-04  895.0  908.0  870.0  875.0  678.447571   70300
1  2012-01-05  875.0  881.0  863.0  878.0  680.773499   46300
2  2012-01-06  870.0  877.0  855.0  870.0  674.570618   28800
3  2012-01-10  871.0  893.0  871.0  884.0  685.425781   65600
4  2012-01-11  884.0  930.0  879.0  928.0  719.541809  131100

In [6]:
df['Volume'].value_counts()

Volume
0         24
27700     12
38900     12
66200     11
49300     10
          ..
281000     1
144900     1
10300      1
8500       1
227000     1
Name: count, Length: 1157, dtype: int64

In [7]:
cat_col = 'Volume'

label_encoder = LabelEncoder()
df['Volume_label_encoded'] = label_encoder.fit_transform(df[cat_col])

mapping = dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)))
print("Соответствие значений и меток:")
print(mapping)

df[[cat_col, 'Volume_label_encoded']].head()

Соответствие значений и меток:

   Volume  Volume_label_encoded
0   70300                   587
1   46300                   354
2   28800                   182
3   65600                   542
4  131100                   970

Задача 24

In [8]:
volume = df['Volume']

lower_bound = volume.quantile(0.05)
upper_bound = volume.quantile(0.95)

print("Нижняя граница по 5% квантилю:", lower_bound)
print("Верхняя граница по 95% квантилю:", upper_bound)

outliers = df[(volume < lower_bound) | (volume > upper_bound)]

print("\nОбнаруженные выбросы:")
print(outliers)

df_filtered = df[(volume >= lower_bound) & (volume <= upper_bound)]

print("\nНабор данных после удаления выбросов:")
print(df_filtered)

Нижняя граница по 5% квантилю: 16700.0
Верхняя граница по 95% квантилю: 144424.9999999999

Обнаруженные выбросы:
            Date    Open    High     Low   Close    Adj Close  Volume  \
7     2012-01-16   926.0   990.0   918.0   990.0   767.614807  217000
8     2012-01-17  1000.0  1027.0   994.0  1017.0   788.549683  184400
9     2012-01-18  1014.0  1014.0   910.0   919.0   712.563599  255600
10    2012-01-19   919.0   928.0   888.0   900.0   697.831421  168800
14    2012-01-25   909.0   955.0   909.0   955.0   740.476929  165900
...          ...     ...     ...     ...     ...          ...     ...
3037  2024-05-01  2449.0  2460.0  2405.0  2414.0  2414.000000   10300
3038  2024-05-02  2415.0  2440.0  2406.0  2414.0  2414.000000    8500
3041  2024-05-09  2352.0  2391.0  2350.0  2377.0  2377.000000   14100
3042  2024-05-10  2392.0  2392.0  2361.0  2374.0  2374.000000    9900
3044  2024-05-14  2352.0  2592.0  2333.0  2590.0  2590.000000  227000

      Volume_label_encoded
7                     1111
8                     1076
9                     1129
10                    1060
14                    1053
...                    ...
3037                    15
3038                     8
3041                    42
3042                    13
3044                  1117

[304 rows x 8 columns]

Набор данных после удаления выбросов:
            Date    Open    High     Low   Close    Adj Close  Volume  \
0     2012-01-04   895.0   908.0   870.0   875.0   678.447571   70300
1     2012-01-05   875.0   881.0   863.0   878.0   680.773499   46300
2     2012-01-06   870.0   877.0   855.0   870.0   674.570618   28800
3     2012-01-10   871.0   893.0   871.0   884.0   685.425781   65600
4     2012-01-11   884.0   930.0   879.0   928.0   719.541809  131100
...          ...     ...     ...     ...     ...          ...     ...
3047  2024-05-17  2500.0  2545.0  2480.0  2545.0  2545.000000   23600
3048  2024-05-20  2545.0  2604.0  2545.0  2572.0  2572.000000   27900
3049  2024-05-21  2572.0  2581.0  2507.0  2514.0  2514.000000   23700
3050  2024-05-22  2524.0  2551.0  2520.0  2539.0  2539.000000   17800
3051  2024-05-23  2552.0  2566.0  2525.0  2558.0  2558.000000   24400

      Volume_label_encoded
0                      587
1                      354
2                      182
3                      542
4                      970
...                    ...
3047                   130
3048                   173
3049                   131
3050                    73
3051                   138

[2748 rows x 8 columns]