# Добровольский А.В. ИУ5-23М
## Лабораторная работа №1  
### Предобработка данных: пропуски, категориальные признаки, нормализация

**Задача:** выбрать датасет, содержащий числовые и категориальные признаки, а также пропуски, и выполнить:

1. устранение пропусков в данных;
2. кодирование категориальных признаков;
3. нормализацию числовых признаков.

В работе используется датасет **Automobile** из UCI Machine Learning Repository.  
Он содержит характеристики автомобилей: марка, тип кузова, тип топлива, объём двигателя, мощность, расход топлива, цена и другие признаки.

In [1]:
!pip install pandas scikit-learn

Collecting pandas
  Using cached pandas-3.0.2-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting scikit-learn
  Using cached scikit_learn-1.8.0-cp314-cp314-win_amd64.whl.metadata (11 kB)
Collecting numpy>=2.3.3 (from pandas)
  Using cached numpy-2.4.4-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Using cached tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting scipy>=1.10.0 (from scikit-learn)
  Using cached scipy-1.17.1-cp314-cp314-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: six>=1.5 in .\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.2-cp314-cp314-win_amd64.whl (9.9 MB)
Using cached scikit_learn-1.8.0-cp314-cp314-win_amd64.whl (8.1 MB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Using cached numpy-2.4.4-cp314-cp314-win_amd64.whl (12.4 MB)
Using cached scipy-1.17.1-cp314-cp314-win_amd64.whl (37.3 MB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Using cached tzdata-2026.2-py2.py3-none-any.whl (349 kB)
Installing collected packages: tzdata, threadpoolctl, numpy, joblib, scipy, pandas, scikit-learn

   ---------------------------------------- 0/7 [tzdata]
   ---------------------------------------- 0/7 [tzdata]
   ---------------------------------------- 0/7 [tzdata]
   ---------------------------------------- 0/7 [tzdata]
   ---------------------------------------- 0/7 [tzdata]
   ----- ---------------------------------- 1/7 [threadpoolctl]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------- ---------------------------- 2/7 [numpy]
   ----------------- ---------------------- 3/7 [joblib]
   ----------------- ---------------------- 3/7 [joblib]
   ----------------- ---------------------- 3/7 [joblib]
   ----------------- ---------------------- 3/7 [joblib]
   ----------------- ---------------------- 3/7 [joblib]
   ----------------- ---------------------- 3/7 [joblib]
   ----------------- ---------------------- 3/7 [joblib]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------- ----------------- 4/7 [scipy]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]
   ---------------------------------- ----- 6/7 [scikit-learn]

## Импорт библиотек

In [2]:
import numpy as np
import pandas as pd

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

pd.set_option("display.max_columns", 100)
pd.set_option("display.width", 120)

## Загрузка датасета

У датасета нет заголовков столбцов в `.data`-файле, поэтому названия признаков задаём вручную.

In [3]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data"

columns = [
    "symboling",
    "normalized-losses",
    "make",
    "fuel-type",
    "aspiration",
    "num-of-doors",
    "body-style",
    "drive-wheels",
    "engine-location",
    "wheel-base",
    "length",
    "width",
    "height",
    "curb-weight",
    "engine-type",
    "num-of-cylinders",
    "engine-size",
    "fuel-system",
    "bore",
    "stroke",
    "compression-ratio",
    "horsepower",
    "peak-rpm",
    "city-mpg",
    "highway-mpg",
    "price",
]

df = pd.read_csv(url, names=columns)

df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,52.4,2823,ohcv,six,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,54.3,2337,ohc,four,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,54.3,2824,ohc,five,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

## Первичный анализ данных

In [4]:
print("Размер датасета:", df.shape)
df.info()

Размер датасета: (205, 26)
<class 'pandas.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  205 non-null    str
 2   make               205 non-null    str
 3   fuel-type          205 non-null    str
 4   aspiration         205 non-null    str
 5   num-of-doors       205 non-null    str
 6   body-style         205 non-null    str
 7   drive-wheels       205 non-null    str
 8   engine-location    205 non-null    str
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64
 14  engine-type        205 non-null    str
 15  num-of-cylinders   205 non-null    str
 16  engine-size        205 non-null    int64
 17  fuel-system        205 non-null    str
 18  bore               205 non-null    str
 19  stroke             205 non-null    str
 20  compression-ratio  205 non-null    float64
 21  horsepower         205 non-null    str
 22  peak-rpm           205 non-null    str
 23  city-mpg           205 non-null    int64
 24  highway-mpg        205 non-null    int64
 25  price              205 non-null    str
dtypes: float64(5), int64(5), str(16)
memory usage: 41.8 KB

In [5]:
df.describe(include="all").T.head(15)

                   count unique     top freq         mean         std     min     25%     50%     75%     max
symboling          205.0    NaN     NaN  NaN     0.834146    1.245307    -2.0     0.0     1.0     2.0     3.0
normalized-losses    205     52       ?   41          NaN         NaN     NaN     NaN     NaN     NaN     NaN
make                 205     22  toyota   32          NaN         NaN     NaN     NaN     NaN     NaN     NaN
fuel-type            205      2     gas  185          NaN         NaN     NaN     NaN     NaN     NaN     NaN
aspiration           205      2     std  168          NaN         NaN     NaN     NaN     NaN     NaN     NaN
num-of-doors         205      3    four  114          NaN         NaN     NaN     NaN     NaN     NaN     NaN
body-style           205      5   sedan   96          NaN         NaN     NaN     NaN     NaN     NaN     NaN
drive-wheels         205      3     fwd  120          NaN         NaN     NaN     NaN     NaN     NaN     NaN
engine-location      205      2   front  202          NaN         NaN     NaN     NaN     NaN     NaN     NaN
wheel-base         205.0    NaN     NaN  NaN    98.756585    6.021776    86.6    94.5    97.0   102.4   120.9
length             205.0    NaN     NaN  NaN   174.049268   12.337289   141.1   166.3   173.2   183.1   208.1
width              205.0    NaN     NaN  NaN    65.907805    2.145204    60.3    64.1    65.5    66.9    72.3
height             205.0    NaN     NaN  NaN    53.724878    2.443522    47.8    52.0    54.1    55.5    59.8
curb-weight        205.0    NaN     NaN  NaN  2555.565854  520.680204  1488.0  2145.0  2414.0  2935.0  4066.0
engine-type          205      7     ohc  148          NaN         NaN     NaN     NaN     NaN     NaN     NaN

## Обработка обозначений пропусков и типов данных

В исходном датасете пропуски обозначены символом `?`. Заменим их на стандартное значение `NaN`.

После этого некоторые числовые столбцы всё ещё имеют тип `object`, потому что в них были символы `?`. Преобразуем такие столбцы к числовому типу.

In [6]:
# Заменяем '?' на NaN
df = df.replace("?", np.nan)

# Список числовых столбцов
numeric_columns = [
    "symboling",
    "normalized-losses",
    "wheel-base",
    "length",
    "width",
    "height",
    "curb-weight",
    "engine-size",
    "bore",
    "stroke",
    "compression-ratio",
    "horsepower",
    "peak-rpm",
    "city-mpg",
    "highway-mpg",
    "price",
]

# Преобразуем числовые признаки к типу float/int там, где это возможно
for col in numeric_columns:
    df[col] = pd.to_numeric(df[col], errors="coerce")

df.dtypes

symboling              int64
normalized-losses    float64
make                     str
fuel-type                str
aspiration               str
num-of-doors             str
body-style               str
drive-wheels             str
engine-location          str
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type              str
num-of-cylinders         str
engine-size            int64
fuel-system              str
bore                 float64
stroke               float64
compression-ratio    float64
horsepower           float64
peak-rpm             float64
city-mpg               int64
highway-mpg            int64
price                float64
dtype: object

## Поиск пропусков

Посмотрим, в каких столбцах есть пропущенные значения.

In [7]:
missing_values = (
    df.isna()
    .sum()
    .sort_values(ascending=False)
)

missing_values[missing_values > 0]

normalized-losses    41
stroke                4
price                 4
bore                  4
horsepower            2
peak-rpm              2
num-of-doors          2
dtype: int64

In [8]:
missing_percent = (
    df.isna()
    .mean()
    .mul(100)
    .sort_values(ascending=False)
)

pd.DataFrame({
    "missing_count": missing_values,
    "missing_percent": missing_percent.round(2)
}).query("missing_count > 0")

                   missing_count  missing_percent
normalized-losses             41            20.00
stroke                         4             1.95
price                          4             1.95
bore                           4             1.95
horsepower                     2             0.98
peak-rpm                       2             0.98
num-of-doors                   2             0.98

## Разделение признаков и целевой переменной

В качестве целевой переменной возьмем `price`.

Строки с пропущенной целевой переменной удалим.  
Пропуски в признаках будем устранять с помощью заполнения:

- числовые признаки — медианой;
- категориальные признаки — наиболее частым значением.

In [12]:
target_column = "price"

df_model = df.dropna(subset=[target_column]).copy()

X = df_model.drop(columns=[target_column])
y = df_model[target_column]

numeric_features = X.select_dtypes(include=["int64", "float64"]).columns.tolist()
categorical_features = X.select_dtypes(include=["object"]).columns.tolist()

print("Количество строк после удаления пропусков в target:", X.shape[0])
print("Числовые признаки:", numeric_features)
print("Категориальные признаки:", categorical_features)

Количество строк после удаления пропусков в target: 201
Числовые признаки: ['symboling', 'normalized-losses', 'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-size', 'bore', 'stroke', 'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg', 'highway-mpg']
Категориальные признаки: ['make', 'fuel-type', 'aspiration', 'num-of-doors', 'body-style', 'drive-wheels', 'engine-location', 'engine-type', 'num-of-cylinders', 'fuel-system']

C:\Users\Nendhelm\AppData\Local\Temp\ipykernel_1604\939987410.py:9: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_features = X.select_dtypes(include=["object"]).columns.tolist()

## Устранение пропусков в данных

Заполним пропуски отдельно для числовых и категориальных признаков:

- для числовых признаков используем `median`, так как медиана устойчива к выбросам;
- для категориальных признаков используем `most_frequent`, то есть самое частое значение.

In [13]:
X_imputed = X.copy()

num_imputer = SimpleImputer(strategy="median")
cat_imputer = SimpleImputer(strategy="most_frequent")

X_imputed[numeric_features] = num_imputer.fit_transform(X_imputed[numeric_features])
X_imputed[categorical_features] = cat_imputer.fit_transform(X_imputed[categorical_features])

print("Количество пропусков до обработки:", X.isna().sum().sum())
print("Количество пропусков после обработки:", X_imputed.isna().sum().sum())

Количество пропусков до обработки: 51
Количество пропусков после обработки: 0

In [14]:
# Проверка
X_imputed.isna().sum().sort_values(ascending=False).head()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
aspiration           0
dtype: int64

## Кодирование категориальных признаков

Для категориальных признаков применим **One-Hot Encoding**.

Этот метод создаёт отдельный бинарный столбец для каждой категории.  
Например, признак `fuel-type` со значениями `gas` и `diesel` превратится в два столбца:

- `fuel-type_gas`;
- `fuel-type_diesel`.

In [ ]:
try:
    encoder = OneHotEncoder(handle_unknown="ignore", sparse_output=False)
except TypeError:
    encoder = OneHotEncoder(handle_unknown="ignore", sparse=False)

encoded_array = encoder.fit_transform(X_imputed[categorical_features])
encoded_columns = encoder.get_feature_names_out(categorical_features)

X_encoded_categorical = pd.DataFrame(
    encoded_array,
    columns=encoded_columns,
    index=X_imputed.index
)

X_encoded = pd.concat(
    [
        X_imputed[numeric_features],
        X_encoded_categorical
    ],
    axis=1
)

print("Размер данных до кодирования:", X_imputed.shape)
print("Размер данных после кодирования:", X_encoded.shape)

X_encoded.head()

Размер данных до кодирования: (201, 25)
Размер данных после кодирования: (201, 74)

,symboling,normalized-losses,wheel-base,length,width,height,curb-weight,engine-size,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,make_alfa-romero,make_audi,make_bmw,make_chevrolet,make_dodge,make_honda,make_isuzu,make_jaguar,make_mazda,make_mercedes-benz,make_mercury,make_mitsubishi,make_nissan,make_peugot,make_plymouth,make_porsche,make_renault,make_saab,make_subaru,make_toyota,make_volkswagen,make_volvo,fuel-type_diesel,fuel-type_gas,aspiration_std,aspiration_turbo,num-of-doors_four,num-of-doors_two,body-style_convertible,body-style_hardtop,body-style_hatchback,body-style_sedan,body-style_wagon,drive-wheels_4wd,drive-wheels_fwd,drive-wheels_rwd,engine-location_front,engine-location_rear,engine-type_dohc,engine-type_l,engine-type_ohc,engine-type_ohcf,engine-type_ohcv,engine-type_rotor,num-of-cylinders_eight,num-of-cylinders_five,num-of-cylinders_four,num-of-cylinders_six,num-of-cylinders_three,num-of-cylinders_twelve,num-of-cylinders_two,fuel-system_1bbl,fuel-system_2bbl,fuel-system_4bbl,fuel-system_idi,fuel-system_mfi,fuel-system_mpfi,fuel-system_spdi,fuel-system_spfi
0,3.0,115.0,88.6,168.8,64.1,48.8,2548.0,130.0,3.47,2.68,9.0,111.0,5000.0,21.0,27.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,3.0,115.0,88.6,168.8,64.1,48.8,2548.0,130.0,3.47,2.68,9.0,111.0,5000.0,21.0,27.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,1.0,115.0,94.5,171.2,65.5,52.4,2823.0,152.0,2.68,3.47,9.0,154.0,5000.0,19.0,26.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,2.0,164.0,99.8,176.6,66.2,54.3,2337.0,109.0,3.19,3.40,10.0,102.0,5500.0,24.0,30.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,2.0,164.0,99.4,176.6,66.4,54.3,2824.0,136.0,3.19,3.40,8.0,115.0,5500.0,18.0,22.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

## Нормализация числовых признаков

Нормализация нужна, чтобы привести числовые признаки к единому масштабу.

Используем `MinMaxScaler`, который переводит значения в диапазон от 0 до 1:

\[
x_{norm} = \frac{x - x_{min}}{x_{max} - x_{min}}
\]

In [16]:
scaler = MinMaxScaler()

X_normalized = X_encoded.copy()
X_normalized[numeric_features] = scaler.fit_transform(X_normalized[numeric_features])

X_normalized.head()

,symboling,normalized-losses,wheel-base,length,width,height,curb-weight,engine-size,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,make_alfa-romero,make_audi,make_bmw,make_chevrolet,make_dodge,make_honda,make_isuzu,make_jaguar,make_mazda,make_mercedes-benz,make_mercury,make_mitsubishi,make_nissan,make_peugot,make_plymouth,make_porsche,make_renault,make_saab,make_subaru,make_toyota,make_volkswagen,make_volvo,fuel-type_diesel,fuel-type_gas,aspiration_std,aspiration_turbo,num-of-doors_four,num-of-doors_two,body-style_convertible,body-style_hardtop,body-style_hatchback,body-style_sedan,body-style_wagon,drive-wheels_4wd,drive-wheels_fwd,drive-wheels_rwd,engine-location_front,engine-location_rear,engine-type_dohc,engine-type_l,engine-type_ohc,engine-type_ohcf,engine-type_ohcv,engine-type_rotor,num-of-cylinders_eight,num-of-cylinders_five,num-of-cylinders_four,num-of-cylinders_six,num-of-cylinders_three,num-of-cylinders_twelve,num-of-cylinders_two,fuel-system_1bbl,fuel-system_2bbl,fuel-system_4bbl,fuel-system_idi,fuel-system_mfi,fuel-system_mpfi,fuel-system_spdi,fuel-system_spfi
0,1.0,0.261780,0.058309,0.413433,0.324786,0.083333,0.411171,0.260377,0.664286,0.290476,0.1250,0.294393,0.346939,0.222222,0.289474,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,1.0,0.261780,0.058309,0.413433,0.324786,0.083333,0.411171,0.260377,0.664286,0.290476,0.1250,0.294393,0.346939,0.222222,0.289474,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,0.6,0.261780,0.230321,0.449254,0.444444,0.383333,0.517843,0.343396,0.100000,0.666667,0.1250,0.495327,0.346939,0.166667,0.263158,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,0.8,0.518325,0.384840,0.529851,0.504274,0.541667,0.329325,0.181132,0.464286,0.633333,0.1875,0.252336,0.551020,0.305556,0.368421,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,0.8,0.518325,0.373178,0.529851,0.521368,0.541667,0.518231,0.283019,0.464286,0.633333,0.0625,0.313084,0.551020,0.138889,0.157895,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [17]:
# Проверка
pd.DataFrame({
    "min": X_normalized[numeric_features].min(),
    "max": X_normalized[numeric_features].max()
}).head(20)

                   min  max
symboling          0.0  1.0
normalized-losses  0.0  1.0
wheel-base         0.0  1.0
length             0.0  1.0
width              0.0  1.0
height             0.0  1.0
curb-weight        0.0  1.0
engine-size        0.0  1.0
bore               0.0  1.0
stroke             0.0  1.0
compression-ratio  0.0  1.0
horsepower         0.0  1.0
peak-rpm           0.0  1.0
city-mpg           0.0  1.0
highway-mpg        0.0  1.0

## Итоговый датасет после предобработки

В результате:

1. пропуски устранены;
2. категориальные признаки закодированы;
3. числовые признаки нормализованы;
4. данные готовы для дальнейшего обучения модели машинного обучения.

In [18]:
print("Итоговый размер X:", X_normalized.shape)
print("Размер y:", y.shape)
print("Остались ли пропуски в X:", X_normalized.isna().sum().sum())

X_normalized.head()

Итоговый размер X: (201, 74)
Размер y: (201,)
Остались ли пропуски в X: 0

,symboling,normalized-losses,wheel-base,length,width,height,curb-weight,engine-size,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,make_alfa-romero,make_audi,make_bmw,make_chevrolet,make_dodge,make_honda,make_isuzu,make_jaguar,make_mazda,make_mercedes-benz,make_mercury,make_mitsubishi,make_nissan,make_peugot,make_plymouth,make_porsche,make_renault,make_saab,make_subaru,make_toyota,make_volkswagen,make_volvo,fuel-type_diesel,fuel-type_gas,aspiration_std,aspiration_turbo,num-of-doors_four,num-of-doors_two,body-style_convertible,body-style_hardtop,body-style_hatchback,body-style_sedan,body-style_wagon,drive-wheels_4wd,drive-wheels_fwd,drive-wheels_rwd,engine-location_front,engine-location_rear,engine-type_dohc,engine-type_l,engine-type_ohc,engine-type_ohcf,engine-type_ohcv,engine-type_rotor,num-of-cylinders_eight,num-of-cylinders_five,num-of-cylinders_four,num-of-cylinders_six,num-of-cylinders_three,num-of-cylinders_twelve,num-of-cylinders_two,fuel-system_1bbl,fuel-system_2bbl,fuel-system_4bbl,fuel-system_idi,fuel-system_mfi,fuel-system_mpfi,fuel-system_spdi,fuel-system_spfi
0,1.0,0.261780,0.058309,0.413433,0.324786,0.083333,0.411171,0.260377,0.664286,0.290476,0.1250,0.294393,0.346939,0.222222,0.289474,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,1.0,0.261780,0.058309,0.413433,0.324786,0.083333,0.411171,0.260377,0.664286,0.290476,0.1250,0.294393,0.346939,0.222222,0.289474,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,0.6,0.261780,0.230321,0.449254,0.444444,0.383333,0.517843,0.343396,0.100000,0.666667,0.1250,0.495327,0.346939,0.166667,0.263158,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,0.8,0.518325,0.384840,0.529851,0.504274,0.541667,0.329325,0.181132,0.464286,0.633333,0.1875,0.252336,0.551020,0.305556,0.368421,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,0.8,0.518325,0.373178,0.529851,0.521368,0.541667,0.518231,0.283019,0.464286,0.633333,0.0625,0.313084,0.551020,0.138889,0.157895,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0